# Generated by Django 5.2.17 on 2026-10-05 23:41

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("contacto", models.CharField(blank=True, max_length=255)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("usuario_nombre", models.CharField(blank=True, max_length=150)),
                ("rol", models.CharField(blank=True, max_length=20)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("accion", models.CharField(db_index=True, max_length=40)),
                ("objeto", models.CharField(max_length=40)),
                ("objeto_id", models.CharField(blank=True, max_length=40)),
                ("objeto_repr", models.CharField(blank=True, max_length=255)),
                (
                    "cliente_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("antes", models.JSONField(blank=True, null=True)),
                ("despues", models.JSONField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "auditoría",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCliente",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=150)),
                ("contacto", models.CharField(blank=True, max_length=255)),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cliente",
                "verbose_name_plural": "historical clientes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMatafuego",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("numero_serie", models.CharField(max_length=60)),
                ("clase", models.CharField(blank=True, max_length=30)),
                ("ubicacion", models.CharField(blank=True, max_length=200)),
                ("vencimiento_carga", models.DateField(blank=True, null=True)),
                ("vencimiento_ph", models.DateField(blank=True, null=True)),
                (
                    "token_qr",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.cliente",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical matafuego",
                "verbose_name_plural": "historical matafuegos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPerfil",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("OFICINA", "Oficina/Editor"),
                            ("OPERARIO", "Operario de campo"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical perfil",
                "verbose_name_plural": "historical perfils",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Matafuego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_serie", models.CharField(max_length=60)),
                ("clase", models.CharField(blank=True, max_length=30)),
                ("ubicacion", models.CharField(blank=True, max_length=200)),
                ("vencimiento_carga", models.DateField(blank=True, null=True)),
                ("vencimiento_ph", models.DateField(blank=True, null=True)),
                (
                    "token_qr",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matafuegos",
                        to="core.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["cliente__nombre", "numero_serie"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTicketSoporte",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=32)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierto"), ("CERRADO", "Cerrado")],
                        default="ABIERTO",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matafuego",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.matafuego",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ticket soporte",
                "verbose_name_plural": "historical ticket soportes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "presion",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("NORMAL", "Normal"),
                            ("ALTA", "Alta"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("senalizacion", models.BooleanField(default=True)),
                ("chapa_baliza", models.BooleanField(default=True)),
                ("accesible", models.BooleanField(default=True)),
                ("observaciones", models.TextField(blank=True)),
                ("ubicacion", models.CharField(blank=True, max_length=200)),
                ("vencimiento_carga", models.DateField(blank=True, null=True)),
                ("vencimiento_ph", models.DateField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matafuego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controles",
                        to="core.matafuego",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("OFICINA", "Oficina/Editor"),
                            ("OPERARIO", "Operario de campo"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "clientes",
                    models.ManyToManyField(
                        blank=True, related_name="perfiles", to="core.cliente"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketSoporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=32)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierto"), ("CERRADO", "Cerrado")],
                        default="ABIERTO",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="core.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matafuego",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="core.matafuego",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MensajeChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_soporte", models.BooleanField(default=False)),
                ("texto", models.TextField(max_length=3000)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensajes_chat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="core.ticketsoporte",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="matafuego",
            constraint=models.UniqueConstraint(
                fields=("cliente", "numero_serie"), name="uniq_serie_por_cliente"
            ),
        ),
    ]
